import { MapObject, MaterialOverride, MaterialTextOverride, StreamerConfig } from '@/types/editor';
import { getObjectInfo } from '@/data/sampObjects';

/**
 * Converts web hex color (#RRGGBB or #RRGGBBAA) to SA-MP ARGB hex string (0xAARRGGBB)
 */
export function hexToSampArgb(hex: string): string {
  let cleanHex = hex.replace('#', '').trim();
  if (cleanHex.startsWith('0x') || cleanHex.startsWith('0X')) {
    cleanHex = cleanHex.substring(2);
  }

  if (cleanHex.length === 6) {
    // RRGGBB -> 0xFFRRGGBB
    return `0xFF${cleanHex.toUpperCase()}`;
  } else if (cleanHex.length === 8) {
    // RRGGBBAA -> 0xAARRGGBB
    const rr = cleanHex.substring(0, 2);
    const gg = cleanHex.substring(2, 4);
    const bb = cleanHex.substring(4, 6);
    const aa = cleanHex.substring(6, 8);
    return `0x${aa}${rr}${gg}${bb}`.toUpperCase();
  }
  return '0xFFFFFFFF';
}

/**
 * Converts SA-MP ARGB integer / hex to web hex color (#RRGGBB)
 */
export function sampArgbToHex(sampColor: string | number): string {
  if (typeof sampColor === 'string') {
    sampColor = sampColor.trim();
    if (sampColor.startsWith('#')) return sampColor;
    if (sampColor.toLowerCase().startsWith('0x')) {
      const hex = sampColor.substring(2).padStart(8, '0');
      // ARGB -> RRGGBB
      return `#${hex.substring(2, 8)}`;
    }
    const parsed = parseInt(sampColor, 10);
    if (!isNaN(parsed)) {
      sampColor = parsed;
    }
  }

  if (typeof sampColor === 'number') {
    // Handle signed 32-bit int from Pawn (e.g., -1 for 0xFFFFFFFF)
    const uint32 = sampColor >>> 0;
    const hex = uint32.toString(16).padStart(8, '0');
    return `#${hex.substring(2, 8)}`;
  }

  return '#FFFFFF';
}

/**
 * Generates SA-MP Pawn script (Streamer plugin format)
 */
export function exportToPawn(
  objects: MapObject[],
  config: StreamerConfig = {
    worldId: -1,
    interiorId: -1,
    playerId: -1,
    streamDistance: 300.0,
    drawDistance: 300.0,
    variableName: 'obj',
    offsetX: 0.0,
    offsetY: 0.0,
    offsetZ: 1000.0
  },
  useNative: boolean = false
): string {
  const offX = config.offsetX ?? 0.0;
  const offY = config.offsetY ?? 0.0;
  const offZ = config.offsetZ ?? 1000.0;

  const lines: string[] = [];
  lines.push('// ==============================================================================');
  lines.push('// SA-MP / open.mp Map Export');
  lines.push(`// Total Objects: ${objects.length}`);
  lines.push(`// Base Elevation Offset: X: ${offX.toFixed(2)}, Y: ${offY.toFixed(2)}, Z: ${offZ.toFixed(2)} ${offZ >= 500 ? '(Sky Safe - Zero Ground Collision)' : ''}`);
  lines.push('// In-game Teleport Coordinates for Admin / Scripter:');
  lines.push(`//   SetPlayerPos(playerid, ${offX.toFixed(4)}, ${offY.toFixed(4)}, ${(offZ + 1.0).toFixed(4)});`);
  lines.push(`//   SetPlayerVirtualWorld(playerid, ${config.worldId});`);
  lines.push(`//   SetPlayerInterior(playerid, ${config.interiorId});`);
  lines.push('// Generated by SA-MP 3D Interior & Universal Map Editor');
  lines.push('// ==============================================================================\n');

  lines.push('// Include necessary headers if not already present:');
  if (useNative) {
    lines.push('// #include <a_samp>\n');
  } else {
    lines.push('// #include <streamer>\n');
  }

  lines.push('public OnGameModeInit()');
  lines.push('{');
  lines.push(`    new ${config.variableName};`);
  lines.push('');

  objects.forEach((obj, idx) => {
    const x = (obj.position[0] + offX).toFixed(4);
    const y = (obj.position[1] + offY).toFixed(4);
    const z = (obj.position[2] + offZ).toFixed(4);
    const rx = obj.rotation[0].toFixed(4);
    const ry = obj.rotation[1].toFixed(4);
    const rz = obj.rotation[2].toFixed(4);

    lines.push(`    // [${idx + 1}] ${obj.name} (Model: ${obj.modelId})`);
    if (useNative) {
      lines.push(`    ${config.variableName} = CreateObject(${obj.modelId}, ${x}, ${y}, ${z}, ${rx}, ${ry}, ${rz}, ${config.drawDistance.toFixed(1)});`);
    } else {
      lines.push(
        `    ${config.variableName} = CreateDynamicObject(${obj.modelId}, ${x}, ${y}, ${z}, ${rx}, ${ry}, ${rz}, ${config.worldId}, ${config.interiorId}, ${config.playerId}, ${config.streamDistance.toFixed(1)}, ${config.drawDistance.toFixed(1)});`
      );
    }

    // Material overrides
    const matIndices = Object.keys(obj.materials).map(Number).sort((a, b) => a - b);
    for (const matIdx of matIndices) {
      const mat = obj.materials[matIdx];
      const argb = hexToSampArgb(mat.color);
      if (useNative) {
        lines.push(
          `    SetObjectMaterial(${config.variableName}, ${mat.index}, ${mat.modelId}, "${mat.txdName}", "${mat.textureName}", ${argb});`
        );
      } else {
        lines.push(
          `    SetDynamicObjectMaterial(${config.variableName}, ${mat.index}, ${mat.modelId}, "${mat.txdName}", "${mat.textureName}", ${argb});`
        );
      }
    }

    // Material text overrides
    const textIndices = Object.keys(obj.materialTexts).map(Number).sort((a, b) => a - b);
    for (const tIdx of textIndices) {
      const t = obj.materialTexts[tIdx];
      const fColor = hexToSampArgb(t.fontColor);
      const bColor = hexToSampArgb(t.backColor);
      const boldFlag = t.bold ? 1 : 0;
      if (useNative) {
        lines.push(
          `    SetObjectMaterialText(${config.variableName}, "${t.text}", ${t.index}, ${t.size}, "${t.font}", ${t.fontSize}, ${boldFlag}, ${fColor}, ${bColor}, ${t.align});`
        );
      } else {
        lines.push(
          `    SetDynamicObjectMaterialText(${config.variableName}, ${t.index}, "${t.text}", ${t.size}, "${t.font}", ${t.fontSize}, ${boldFlag}, ${fColor}, ${bColor}, ${t.align});`
        );
      }
    }

    lines.push('');
  });

  lines.push('    return 1;');
  lines.push('}');
  return lines.join('\n');
}

/**
 * Parses raw Pawn script containing CreateDynamicObject or CreateObject
 */
export function importFromPawn(pawnCode: string): MapObject[] {
  const importedObjects: MapObject[] = [];
  const lines = pawnCode.split('\n');

  let currentObj: MapObject | null = null;

  // Regex to match CreateDynamicObject or CreateObject
  // Matches: Create(Dynamic)?Object\s*\(\s*(\d+)\s*,\s*([-\d.]+)\s*,\s*([-\d.]+)\s*,\s*([-\d.]+)\s*,\s*([-\d.]+)\s*,\s*([-\d.]+)\s*,\s*([-\d.]+)/i
  const createRegex = /(?:CreateDynamicObject|CreateObject)\s*\(\s*(\d+)\s*,\s*([-\d.]+)\s*,\s*([-\d.]+)\s*,\s*([-\d.]+)\s*,\s*([-\d.]+)\s*,\s*([-\d.]+)\s*,\s*([-\d.]+)/i;

  // Regex for Set(Dynamic)?ObjectMaterial
  // Matches: Set(?:Dynamic)?ObjectMaterial\s*\([^,]+,\s*(\d+)\s*,\s*(\d+)\s*,\s*"([^"]+)"\s*,\s*"([^"]+)"\s*,\s*([0-9a-fA-FxX-]+)/i
  const matRegex = /Set(?:Dynamic)?ObjectMaterial\s*\([^,]+,\s*(\d+)\s*,\s*(\d+)\s*,\s*"([^"]+)"\s*,\s*"([^"]+)"\s*,\s*([0-9a-fA-FxX-]+)/i;

  // Regex for Set(Dynamic)?ObjectMaterialText
  const textRegex = /Set(?:Dynamic)?ObjectMaterialText\s*\([^,]+,\s*(\d+)\s*,\s*"([^"]+)"\s*,\s*(\d+)\s*,\s*"([^"]+)"\s*,\s*(\d+)\s*,\s*(\d+)\s*,\s*([0-9a-fA-FxX-]+)\s*,\s*([0-9a-fA-FxX-]+)/i;

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i].trim();
    if (!line || line.startsWith('//') || line.startsWith('/*')) continue;

    const createMatch = line.match(createRegex);
    if (createMatch) {
      const modelId = parseInt(createMatch[1], 10);
      const x = parseFloat(createMatch[2]);
      const y = parseFloat(createMatch[3]);
      const z = parseFloat(createMatch[4]);
      const rx = parseFloat(createMatch[5]);
      const ry = parseFloat(createMatch[6]);
      const rz = parseFloat(createMatch[7]);

      const info = getObjectInfo(modelId);
      const dimensions = info ? info.dimensions : [1.0, 1.0, 1.0];
      const name = info ? info.name : `Object_${modelId}`;

      currentObj = {
        id: `obj_${Date.now()}_${Math.random().toString(36).substring(2, 7)}`,
        modelId,
        name,
        category: info?.category || 'props',
        position: [x, y, z],
        rotation: [rx, ry, rz],
        dimensions: [dimensions[0], dimensions[1], dimensions[2]],
        materials: {},
        materialTexts: {},
        visible: true,
        locked: false
      };

      importedObjects.push(currentObj);
      continue;
    }

    if (currentObj) {
      const matMatch = line.match(matRegex);
      if (matMatch) {
        const matIdx = parseInt(matMatch[1], 10);
        const refModelId = parseInt(matMatch[2], 10);
        const txd = matMatch[3];
        const texture = matMatch[4];
        const colorArg = matMatch[5];

        currentObj.materials[matIdx] = {
          index: matIdx,
          modelId: refModelId,
          txdName: txd,
          textureName: texture,
          color: sampArgbToHex(colorArg)
        };
        continue;
      }

      const textMatch = line.match(textRegex);
      if (textMatch) {
        const textIdx = parseInt(textMatch[1], 10);
        const textStr = textMatch[2];
        const matSize = parseInt(textMatch[3], 10);
        const fontName = textMatch[4];
        const fSize = parseInt(textMatch[5], 10);
        const isBold = parseInt(textMatch[6], 10) === 1;
        const fontCol = sampArgbToHex(textMatch[7]);
        const backCol = sampArgbToHex(textMatch[8]);

        currentObj.materialTexts[textIdx] = {
          index: textIdx,
          text: textStr,
          size: matSize,
          font: fontName,
          fontSize: fSize,
          bold: isBold,
          fontColor: fontCol,
          backColor: backCol,
          align: 1
        };
        continue;
      }
    }
  }

  return importedObjects;
}
